Repository Daily-Boram/daily-boram-spring, pull requests merged in 2022-11, with the labels that each got.

#9 (#7) naver auth token 발급
  build.gradle
  src/main/java/com/example/dailyboramspring/DailyBoramSpringApplication.java
  src/main/java/com/example/dailyboramspring/domain/user/domain/User.java
  src/main/java/com/example/dailyboramspring/domain/user/domain/repository/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/dailyboramspring/domain/user/exception/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/user/exception/UserNotFoundException.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/user/presentation/UserController.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/dto/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/user/presentation/dto/request/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/user/presentation/dto/response/TokenResponse.java
  src/main/java/com/example/dailyboramspring/domain/user/service/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/user/service/NaverAuthService.java
  src/main/java/com/example/dailyboramspring/global/config/ConfigurationConfig.java
  src/main/java/com/example/dailyboramspring/global/config/FilterConfig.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
  src/main/java/com/example/dailyboramspring/global/error/ExceptionFilter.java
  src/main/java/com/example/dailyboramspring/global/exception/ExpiredJwtException.java
  src/main/java/com/example/dailyboramspring/global/exception/InValidJwtException.java
  src/main/java/com/example/dailyboramspring/global/properties/NaverProperties.java
  src/main/java/com/example/dailyboramspring/global/security/auth/AuthDetails.java
  src/main/java/com/example/dailyboramspring/global/security/auth/AuthDetailsService.java
  src/main/java/com/example/dailyboramspring/global/security/jwt/JwtProperties.java
  src/main/java/com/example/dailyboramspring/global/security/jwt/JwtTokenFilter.java
  src/main/java/com/example/dailyboramspring/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/dailyboramspring/infrastructure/feign/client/NaverAuthClient.java
  src/main/java/com/example/dailyboramspring/infrastructure/feign/client/NaverGetClient.java
  src/main/java/com/example/dailyboramspring/infrastructure/feign/dto/NaverAuthResponse.java
  src/main/java/com/example/dailyboramspring/infrastructure/feign/dto/NaverUserResponse.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/example/dailyboramspring/DailyBoramSpringApplicationTests.java
Labels: 기능 추가

#26 🔀 :: (#16) series like entity 생성
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/SeriesLike.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/SeriesLikeId.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/repository/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/repository/SeriesLikeRepository.java
Labels: 기능 추가

#30 🔀 :: (#29) episode entity 생성
  src/main/java/com/example/dailyboramspring/domain/episode/domain/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episode/domain/Episode.java
  src/main/java/com/example/dailyboramspring/domain/episode/domain/repository/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episode/domain/repository/EpisodeRepository.java
Labels: 기능 추가

#28 🔀 :: (#24) genre entity 생성
  src/main/java/com/example/dailyboramspring/domain/genre/domain/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/genre/domain/Genre.java
  src/main/java/com/example/dailyboramspring/domain/genre/domain/repository/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/genre/domain/repository/GenreRepository.java
Labels: 기능 추가

#32 🔀 :: (#31) Character Entity 생성
  src/main/java/com/example/dailyboramspring/domain/character/domain/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/character/domain/Character.java
  src/main/java/com/example/dailyboramspring/domain/character/domain/repository/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/character/domain/repository/CharacterRepository.java
Labels: 기능 추가

#38 🔀 :: (#36) purchase entity 생성
  src/main/java/com/example/dailyboramspring/domain/genre/domain/repository/GenreRepository.java
  src/main/java/com/example/dailyboramspring/domain/purchase/domain/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/purchase/domain/Purchase.java
  src/main/java/com/example/dailyboramspring/domain/purchase/domain/repository/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/purchase/domain/repository/PurchaseRepository.java
Labels: 기능 추가

#45 🔀 :: (#44) 프로필 읽어오기 API 생성
  src/main/java/com/example/dailyboramspring/domain/character/domain/Character.java
  src/main/java/com/example/dailyboramspring/domain/character/domain/repository/CharacterRepository.java
  src/main/java/com/example/dailyboramspring/domain/genre/domain/Genre.java
  src/main/java/com/example/dailyboramspring/domain/profile/domain/Profile.java
  src/main/java/com/example/dailyboramspring/domain/profile/exception/UserNotFoundException.java
  src/main/java/com/example/dailyboramspring/domain/profile/facade/ProfileFacade.java
  src/main/java/com/example/dailyboramspring/domain/profile/presentation/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/profile/presentation/ProfileController.java
  src/main/java/com/example/dailyboramspring/domain/profile/presentation/dto/response/SeriesElement.java
  src/main/java/com/example/dailyboramspring/domain/profile/presentation/dto/response/UserProfileResponse.java
  src/main/java/com/example/dailyboramspring/domain/profile/service/GetUserProfileService.java
  src/main/java/com/example/dailyboramspring/domain/series/domain/repository/SeriesRepository.java
  src/main/java/com/example/dailyboramspring/domain/series/facade/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/series/facade/SeriesFacade.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/repository/SeriesLikeRepository.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/facade/SeriesLikeFacade.java
  src/main/java/com/example/dailyboramspring/domain/user/facade/UserFacade.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
Labels: 기능 추가

#43 🔀 :: (#42) create episode api
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/EpisodeController.java
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/dto/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/dto/request/CreateEpisodeRequest.java
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/dto/response/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episode/service/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episode/service/CreateEpisodeService.java
  src/main/java/com/example/dailyboramspring/domain/series/domain/Series.java
  src/main/java/com/example/dailyboramspring/domain/series/domain/repository/SeriesRepository.java
  src/main/java/com/example/dailyboramspring/domain/series/exception/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/series/exception/SeriesNotFoundException.java
  src/main/java/com/example/dailyboramspring/domain/series/facade/SeriesFacade.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
  src/main/java/com/example/dailyboramspring/global/error/exception/ErrorCode.java
Labels: 기능 추가

#50 🔀 :: (#49) 프로필 수정 API 생성
  src/main/java/com/example/dailyboramspring/domain/profile/domain/Profile.java
  src/main/java/com/example/dailyboramspring/domain/profile/domain/repository/ProfileRepository.java
  src/main/java/com/example/dailyboramspring/domain/profile/exception/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/profile/exception/NicknameOverlapException.java
  src/main/java/com/example/dailyboramspring/domain/profile/facade/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/profile/facade/ProfileFacade.java
  src/main/java/com/example/dailyboramspring/domain/profile/presentation/ProfileController.java
  src/main/java/com/example/dailyboramspring/domain/profile/presentation/dto/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/profile/presentation/dto/request/UpdateProfileRequest.java
  src/main/java/com/example/dailyboramspring/domain/profile/service/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/profile/service/UpdateProfileService.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/SeriesController.java
  src/main/java/com/example/dailyboramspring/domain/series/service/CreateSeries.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
Labels: 기능 추가

#53 🔀 :: (#52) 회차 좋아요 API 생성
  src/main/java/com/example/dailyboramspring/domain/episode/exception/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episode/exception/EpisodeNotFoundException.java
  src/main/java/com/example/dailyboramspring/domain/episode/facade/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episode/facade/EpisodeFacade.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/domain/EpisodeLikeId.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/presentation/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episodelike/presentation/SeriesLikeController.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/service/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episodelike/service/PostEpisodeLikeService.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/SeriesLike.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/presentation/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/serieslike/service/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
  src/main/java/com/example/dailyboramspring/global/error/exception/ErrorCode.java
Labels: 기능 추가

#55 🔀 :: (#54) 프로필 유저 엔티티 병합
  src/main/java/com/example/dailyboramspring/domain/profile/domain/Profile.java
  src/main/java/com/example/dailyboramspring/domain/profile/domain/repository/ProfileRepository.java
  src/main/java/com/example/dailyboramspring/domain/profile/exception/UserNotFoundException.java
  src/main/java/com/example/dailyboramspring/domain/profile/facade/ProfileFacade.java
  src/main/java/com/example/dailyboramspring/domain/profile/presentation/ProfileController.java
  src/main/java/com/example/dailyboramspring/domain/profile/service/UpdateProfileService.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/SeriesLike.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/facade/SeriesLikeFacade.java
  src/main/java/com/example/dailyboramspring/domain/user/domain/User.java
  src/main/java/com/example/dailyboramspring/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/dailyboramspring/domain/user/exception/NicknameOverlapException.java
  src/main/java/com/example/dailyboramspring/domain/user/facade/UserFacade.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/UserController.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/dto/request/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/user/presentation/dto/request/UpdateProfileRequest.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/dto/response/MyUserProfileResponse.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/dto/response/PurchaseElement.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/dto/response/SeriesElement.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/dto/response/UserProfileResponse.java
  src/main/java/com/example/dailyboramspring/domain/user/service/GetMyUserProfileService.java
  src/main/java/com/example/dailyboramspring/domain/user/service/GetUserProfileService.java
  src/main/java/com/example/dailyboramspring/domain/user/service/NaverAuthService.java
  src/main/java/com/example/dailyboramspring/domain/user/service/UpdateProfileService.java
Labels: 기능 추가

#56 🔀 :: (#46) 회차 보기 api
  src/main/java/com/example/dailyboramspring/domain/content/domain/repository/ContentRepository.java
  src/main/java/com/example/dailyboramspring/domain/content/facade/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/content/facade/ContentFacade.java
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/EpisodeController.java
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/dto/response/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/dto/response/ContentList.java
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/dto/response/GetEpisodeResponse.java
  src/main/java/com/example/dailyboramspring/domain/episode/service/GetEpisodeService.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/domain/repository/EpisodeLikeRepository.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/facade/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/episodelike/facade/EpisodeLikeFacade.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
Labels: 기능 추가

#59 🔀 :: (#57) 회차 좋아요 삭제 API 생성
  src/main/java/com/example/dailyboramspring/domain/episodelike/domain/repository/EpisodeLikeRepository.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/exception/EpisodeLikeNotFoundException.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/facade/EpisodeLikeFacade.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/presentation/EpisodeLikeController.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/service/DeleteEpisodeLikeService.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
  src/main/java/com/example/dailyboramspring/global/error/exception/ErrorCode.java
Labels: 기능 추가

#60 🔀 :: (#58) 시리즈 버그 수정
  src/main/java/com/example/dailyboramspring/domain/genre/domain/Genre.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/SeriesController.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/dto/requset/CreateSeriesRequest.java
  src/main/java/com/example/dailyboramspring/domain/series/service/CreateSeries.java
Labels: 버그

#62 🔀 :: (#61) 시리즈 좋아요 API 생성
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/SeriesLikeId.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/presentation/SeriesLikeController.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/presentation/dto/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/serieslike/service/PostSeriesLikeService.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
Labels: 기능 추가

#65 🔀 :: (#63) 회차 대사 추가 api
  src/main/java/com/example/dailyboramspring/domain/character/exception/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/character/exception/CharacterNotFoundException.java
  src/main/java/com/example/dailyboramspring/domain/character/facade/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/character/facade/CharacterFacade.java
  src/main/java/com/example/dailyboramspring/domain/content/presentation/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/content/presentation/ContentController.java
  src/main/java/com/example/dailyboramspring/domain/content/presentation/dto/request/CreateContentRequest.java
  src/main/java/com/example/dailyboramspring/domain/content/service/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/content/service/CreateContentService.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
  src/main/java/com/example/dailyboramspring/global/error/exception/ErrorCode.java
Labels: 기능 추가

#67 🔀 :: (#66) 서비스 메서드 transaction 리펙토링
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/EpisodeController.java
  src/main/java/com/example/dailyboramspring/domain/episode/service/CreateEpisodeService.java
  src/main/java/com/example/dailyboramspring/domain/episode/service/GetEpisodeService.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/UserController.java
  src/main/java/com/example/dailyboramspring/domain/user/service/GetMyUserProfileService.java
  src/main/java/com/example/dailyboramspring/domain/user/service/GetUserProfileService.java
  src/main/java/com/example/dailyboramspring/domain/user/service/NaverAuthService.java
  src/main/java/com/example/dailyboramspring/domain/user/service/UpdateProfileService.java
Labels: 리팩토링

#69 🔀 :: (#64) 시리즈 좋아요 삭제 API 생성
  src/main/java/com/example/dailyboramspring/domain/episodelike/exception/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/repository/SeriesLikeRepository.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/exception/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/serieslike/exception/SeriesLikeNotFoundException.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/facade/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/serieslike/facade/SeriesLikeFacade.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/presentation/SeriesLikeController.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/service/DeleteSeriesLikeService.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
  src/main/java/com/example/dailyboramspring/global/error/exception/ErrorCode.java
Labels: 기능 추가

#71 🔀 :: (#68) episode 인물 추가 api
  src/main/java/com/example/dailyboramspring/domain/character/presentation/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/character/presentation/CharacterController.java
  src/main/java/com/example/dailyboramspring/domain/character/presentation/dto/request/CreateCharacterRequest.java
  src/main/java/com/example/dailyboramspring/domain/character/service/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/character/service/CreateCharacterService.java
  src/main/java/com/example/dailyboramspring/domain/user/exception/ForbiddenUserException.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
  src/main/java/com/example/dailyboramspring/global/error/exception/ErrorCode.java
Labels: 기능 추가

#75 🔀 :: (#73) Episode BaseTimeEntity 상속
  src/main/java/com/example/dailyboramspring/domain/episode/domain/Episode.java
Labels: 기능 추가

#78 🔀 ::(#77) ResponseEntity로 token api 반환
  src/main/java/com/example/dailyboramspring/domain/user/presentation/UserController.java
  src/main/java/com/example/dailyboramspring/domain/user/service/NaverAuthService.java
Labels: 리팩토링

#82 🔀 :: (#81) Comment 삭제 API 생성
  src/main/java/com/example/dailyboramspring/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/example/dailyboramspring/domain/comment/exception/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/example/dailyboramspring/domain/comment/facade/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/comment/facade/CommentFacade.java
  src/main/java/com/example/dailyboramspring/domain/comment/presentation/CommentController.java
  src/main/java/com/example/dailyboramspring/domain/comment/service/DeleteCommentService.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
Labels: 기능 추가

#84 🔀 :: (#80) 시리즈 검색 api
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/dto/response/ContentListElement.java
  src/main/java/com/example/dailyboramspring/domain/episode/presentation/dto/response/GetEpisodeResponse.java
  src/main/java/com/example/dailyboramspring/domain/episode/service/GetEpisodeService.java
  src/main/java/com/example/dailyboramspring/domain/genre/domain/repository/GenreRepository.java
  src/main/java/com/example/dailyboramspring/domain/genre/facade/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/genre/facade/GenreFacade.java
  src/main/java/com/example/dailyboramspring/domain/series/domain/repository/SeriesRepository.java
  src/main/java/com/example/dailyboramspring/domain/series/facade/SeriesFacade.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/SearchSeriesController.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/dto/response/FeedListElement.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/dto/response/SearchSeriesResponse.java
  src/main/java/com/example/dailyboramspring/domain/series/service/SearchSeriesService.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/repository/SeriesLikeRepository.java
  src/main/java/com/example/dailyboramspring/domain/user/facade/UserFacade.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
Labels: 기능 추가

#87 🔀 :: (#86) 댓글 보기 API 생성
  src/main/java/com/example/dailyboramspring/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/example/dailyboramspring/domain/comment/facade/CommentFacade.java
  src/main/java/com/example/dailyboramspring/domain/comment/presentation/CommentController.java
  src/main/java/com/example/dailyboramspring/domain/comment/presentation/dto/.gitkeep
  src/main/java/com/example/dailyboramspring/domain/comment/presentation/dto/response/CommentElement.java
  src/main/java/com/example/dailyboramspring/domain/comment/presentation/dto/response/GetCommentResponse.java
  src/main/java/com/example/dailyboramspring/domain/comment/service/DeleteCommentService.java
  src/main/java/com/example/dailyboramspring/domain/comment/service/GetCommentService.java
  src/main/java/com/example/dailyboramspring/domain/episode/domain/repository/EpisodeRepository.java
  src/main/java/com/example/dailyboramspring/domain/series/domain/repository/SeriesRepository.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/SeriesController.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/facade/SeriesLikeFacade.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
Labels: 기능 추가

#89 🔀 :: (#88) 댓글 삭제 API 수정
  src/main/java/com/example/dailyboramspring/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/example/dailyboramspring/domain/comment/facade/CommentFacade.java
  src/main/java/com/example/dailyboramspring/domain/comment/presentation/CommentController.java
  src/main/java/com/example/dailyboramspring/domain/comment/service/DeleteCommentService.java
Labels: 버그

#93 🔀 :: (#92) 코드 리팩토링
  src/main/java/com/example/dailyboramspring/domain/episodelike/presentation/EpisodeLikeController.java
  src/main/java/com/example/dailyboramspring/domain/episodelike/service/CreateEpisodeLikeService.java
  src/main/java/com/example/dailyboramspring/domain/genre/domain/repository/GenreRepository.java
  src/main/java/com/example/dailyboramspring/domain/genre/facade/GenreFacade.java
  src/main/java/com/example/dailyboramspring/domain/series/domain/Series.java
  src/main/java/com/example/dailyboramspring/domain/series/facade/SeriesFacade.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/presentation/SeriesLikeController.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/service/CreateSeriesLikeService.java
  src/main/java/com/example/dailyboramspring/domain/user/presentation/UserController.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
Labels: 리팩토링

#94 🔀 :: (#92) 버그 업데이트
  .github/workflows/CI.yml
  build.gradle
  src/main/java/com/example/dailyboramspring/domain/series/domain/Series.java
  src/main/java/com/example/dailyboramspring/domain/series/domain/repository/SeriesCustom.java
  src/main/java/com/example/dailyboramspring/domain/series/domain/repository/SeriesCustomImpl.java
  src/main/java/com/example/dailyboramspring/domain/series/domain/repository/SeriesRepository.java
  src/main/java/com/example/dailyboramspring/domain/series/facade/SeriesFacade.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/MainPageController.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/SeriesController.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/dto/response/SearchSeriesResponse.java
  src/main/java/com/example/dailyboramspring/domain/series/presentation/dto/response/SeriesDetailResponse.java
  src/main/java/com/example/dailyboramspring/domain/series/service/MainPageSeries.java
  src/main/java/com/example/dailyboramspring/domain/series/service/SearchSeriesService.java
  src/main/java/com/example/dailyboramspring/domain/serieslike/domain/repository/SeriesLikeRepository.java
  src/main/java/com/example/dailyboramspring/global/config/QuerydslConfig.java
  src/main/java/com/example/dailyboramspring/global/config/SecurityConfig.java
Labels: 버그
